### ISSUE TITLE
Responsiveness,Logo

### ISSUE THREAD

**Issue by joshiujjawal22** [samridhi18/snapchat-Login-UI#1]
- Image logo is in Jpg change it into png.

- Header is not responsive at max-width:1000px, it overlaps the logo below width 1000px.

- Round corner of header is looking absurd.

![Screenshot (175)](https://user-images.githubusercontent.com/44023234/84524716-07be4b80-acf8-11ea-8a96-79072aaacc5d.png)

**Comment by samridhi18** [comment]
thanks!! for looking into it and fixing it
